# Generated by Django 6.0.4 on 2026-04-11 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Refugees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('adress', models.CharField(max_length=250)),
                ('age', models.IntegerField()),
                ('religion', models.CharField(choices=[('MU', 'Mulçumano'), ('JU', 'Judeu'), ('CA', 'Católico')], max_length=2)),
                ('political_affiliation', models.CharField(choices=[('ES', 'Esquerda'), ('DI', 'Direita'), ('CE', 'CENTRO')], max_length=2)),
                ('profession', models.CharField(max_length=100)),
                ('number_of_children', models.IntegerField()),
                ('family_income', models.DecimalField(decimal_places=2, max_digits=7)),
                ('education_level', models.CharField(choices=[('sem', 'sem escolaridade'), ('efi', 'ensino fundamental incompleto'), ('efc', 'ensino fundamental completo'), ('emi', 'ensino medio incompleto'), ('emc', 'ensino medio completo'), ('esi', 'ensino superior incompleto'), ('esc', 'ensino superior completo')], max_length=3)),
            ],
        ),
    ]
