# Generated by Django 6.0.4 on 2026-04-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refugees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='refugees',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
