# Generated by Django 6.0.4 on 2026-04-11 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refugees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refugees',
            old_name='adress',
            new_name='address',
        ),
    ]
