# Generated by Django 6.0.4 on 2026-04-11 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refugees', '0002_rename_adress_refugees_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refugees',
            name='education_level',
            field=models.CharField(choices=[('sem', 'Sem escolaridade'), ('efi', 'Ensino fundamental incompleto'), ('efc', 'Ensino fundamental completo'), ('emi', 'Ensino médio incompleto'), ('emc', 'Ensino médio completo'), ('esi', 'Ensino superior incompleto'), ('esc', 'Ensino superior completo')], max_length=3),
        ),
    ]
